apic/config/argocd/classic/apic-prod-instance-app.yaml
apic/environments/ci/pipelines/apic-publish-pipeline.yaml
apic/environments/classic/apic-instance/ibm-apic-single-cluster-prod.yaml
apic/environments/classic/kustomization.yaml
apic/environments/classic/roles/role.yaml
apic/environments/classic/roles/rolebinding.yaml

- Fix in APIC Publish pipeline for git url and yaml url
- Adding APIC on Classic infra

APIC Classic

---

mq/environments/dev/mq-infra/Chart.yaml
mq/environments/dev/mq-infra/requirements.yaml
mq/environments/dev/mq-infra/values.yaml
mq/environments/dev/mq-spring-app/Chart.yaml
mq/environments/dev/mq-spring-app/requirements.yaml
mq/environments/dev/mq-spring-app/values.yaml

Clean up the mq environment directories

---

ace/environments/ci/secrets/git-credentials-secret.sh
scripts/ace-update-git.sh

update sealed secrets

---

mq/environments/ci/secrets/artifactory-access-secret.sh
mq/environments/ci/secrets/artifactory-access-secret.yaml
scripts/mq-kubeseal.sh

Update to scripts and add template artifactory-access-secret.yaml

---

scripts/ace-bootstrap.sh

Signed-off-by: Carlos Santana <csantana23@gmail.com>

fix git pull ace

---

mq/environments/ci/pipelines/ibm-test-pipeline-for-dev.yaml
mq/environments/ci/pipelines/ibm-test-pipeline-for-stage.yaml
mq/environments/ci/pipelines/java-maven-dev-pipeline.yaml
mq/environments/ci/pipelines/mq-pipeline-dev.yaml
mq/environments/ci/pipelines/mq-spring-app-dev-pipeline.yaml
mq/environments/ci/tasks/10-gitops.yaml
mq/environments/ci/tasks/12-functional-tests.yaml
mq/environments/ci/tasks/13-jmeter-performance-test.yaml

Grab latest mq pipelines and tasks from Hema

---

mq/environments/ci/pipelines/ibm-test-pipeline-for-dev.yaml
mq/environments/ci/pipelines/ibm-test-pipeline-for-stage.yaml
mq/environments/ci/pipelines/java-maven-dev-pipeline.yaml
mq/environments/ci/pipelines/mq-pipeline-dev.yaml
mq/environments/ci/pipelines/mq-spring-app-dev-pipeline.yaml

Update default values for pipeline params for MQ

---

mq/environments/ci/pipelines/ibm-test-pipeline-for-dev.yaml
mq/environments/ci/pipelines/ibm-test-pipeline-for-stage.yaml
mq/environments/ci/pipelines/java-maven-dev-pipeline.yaml
mq/environments/ci/pipelines/mq-pipeline-dev.yaml
mq/environments/ci/pipelines/mq-spring-app-dev-pipeline.yaml
mq/environments/ci/tasks/10-gitops.yaml
mq/environments/ci/tasks/12-functional-tests.yaml
mq/environments/ci/tasks/13-jmeter-performance-test.yaml

Add Hema's updates to MQ pipelines and tasks

---

mq/environments/ci/pipelines/ibm-test-pipeline-for-dev.yaml
mq/environments/ci/tasks/12-functional-tests.yaml
mq/environments/ci/tasks/13-jmeter-performance-test.yaml

Grab latest updates from Hema on MQ pipelines

---

mq/environments/ci/pipelines/ibm-test-pipeline-for-dev.yaml
mq/environments/ci/tasks/12-functional-tests.yaml
mq/environments/ci/tasks/13-jmeter-performance-test.yaml

Latest updates to MQ pipelines and tasks from Hema

---

ace/environments/ci/configmaps/gitops-repo-configmap.sh
scripts/ace-bootstrap.sh

Signed-off-by: Carlos Santana <csantana23@gmail.com>

update gitops variables

---

mq/config/argocd/prod/prod-app-rest.yaml
mq/config/argocd/staging/staging-app-rest.yaml

Signed-off-by: Rick Osowski <rosowski@gmail.com>

Corrected staging/prod certificate Apps to correct ns

---

mq/environments/ci/pipelines/ibm-test-pipeline-for-dev.yaml

Issue: https://github.com/cloud-native-toolkit-demos/multi-tenancy-gitops-apps/issues/90

Fix task ref in promotion pipeline

---

apic/environments/multi-cluster/ops/pipelines/apic-config-pipeline.yaml
apic/environments/single-cluster/pipelines/apic-config-pipeline.yaml

Fixing default APIC config pipeline parameters

---

apic/config/argocd/multi-cluster/app/apic-app-multi-cluster.yaml
apic/config/argocd/multi-cluster/ops/apic-pipelines-multi-cluster.yaml
apic/config/argocd/single-cluster/apic-pipelines-single-cluster.yaml

Adding Auto-Sync for app and ops in APIC

---

apic/config/argocd/multi-cluster/app/apic-app-multi-cluster.yaml

revert autosync for apic application

---

mq/environments/ci/eventlisteners/cntk-event-listener.yaml_template
mq/environments/ci/tasks/10-gitops.yaml

Signed-off-by: Hemankita Perabathini <phemankita@gmail.com>

el fix for ocp 4.8

---

mq/environments/ci/tasks/13-jmeter-performance-test.yaml

Signed-off-by: Hemankita Perabathini <phemankita@gmail.com>

moving the jmeter to cloudnativetoolkit

---

apic/config/argocd/single-cluster-cp4i/apic-pipelines-single-cluster.yaml
apic/environments/single-cluster-cp4i/kustomization.yaml
apic/environments/single-cluster-cp4i/pipelines/apic-publish-pipeline.yaml
apic/environments/single-cluster-cp4i/roles/role.yaml
apic/environments/single-cluster-cp4i/roles/rolebinding.yaml
apic/environments/single-cluster-cp4i/tasks/apic-publish-task.yaml

Specific publish pipeline for APIC when deployed with CP4i

---

ace/environments/ci/pipelines/ace-config.yaml
ace/environments/ci/secrets/gitops-repo-pk-secret-template.yaml
ace/environments/ci/secrets/gitops-repo-pk-secret.sh
ace/environments/ci/secrets/gitops-repo-token-secret.sh

commit message describes the changes

Various updates

---

apic/config/argocd/single-cluster-cp4i/apic-pipelines-single-cluster.yaml

Parametres fix

---

mq/environments/mq-infra/overlays/staging/mq-infra/hooks/post-sync-job.yaml_template
mq/environments/mq-spring-app/overlays/dev/mq-spring-app/hooks/post-sync-job.yaml_template

Signed-off-by: Hemankita Perabathini <phemankita@gmail.com>

fix post sync trigger name for staging

---

ace/environments/base/kustomization.yaml
ace/environments/ci/kustomization.yaml

I did add some resources which are required for ACE @hollisc

Adding ACE resources

---

mq/environments/ci/tasks/4-smoke-tests-mq.yaml

Signed-off-by: Anthony ODowd <a_o-dowd@uk.ibm.com>

pass queue manager name betweem steps

---

apic/environments/multi-cluster/ops/tasks/apic-publish-task.yaml

fix for APIC multicloud publish pipeline

---

es/config/argocd/dev/event-streams/dev-event-streams-instance.yaml
es/config/argocd/dev/event-streams/kustomization.yaml
es/config/argocd/dev/kustomization.yaml
es/config/argocd/dev/starter-app/dev-es-starter-app-instance.yaml
es/config/argocd/dev/starter-app/kustomization.yaml
es/environments/base/event-streams/event-streams.yaml
es/environments/base/event-streams/kustomization.yaml
es/environments/base/starter-app/deployment.yaml
es/environments/base/starter-app/kafka-properties.yaml
es/environments/base/starter-app/kustomization.yaml
es/environments/base/starter-app/route.yaml
es/environments/base/starter-app/service.yaml
es/environments/base/starter-app/topic.yaml
es/environments/dev/event-streams/kustomization.yaml
es/environments/dev/starter-app/kustomization.yaml

EventStreams Demo App
